### ISSUE TITLE
Scrollbar big bug

### ISSUE THREAD

**Issue by asc-santo** [nickmilo/LYT-Mode#10]
There is a problem in sliding panes (Andy's mode) with the scrollbar of the note. For me that i use long notes, i usually don't scroll them with the mouse, but i click on the scrollbar and i drag it up and down. The problem is that with this theme the scrollbar is very buggy, it's often much thinner then it should be, and if you open many notes it will often disappear.
This bug apparently seems to be accentuated when clicking on a pane instead of scrolling them from left to right.
At first i thought it was a problem of mine, but i saw it on your video too
https://www.youtube.com/watch?v=vZC7FAOSjkU&t=609s&ab_channel=LinkingYourThinking
At min 6:00 - 6:10 you can clearly see it, especially at 6:10 when you click on the "thinking moc" note, there is no scrollbar at all

**Comment by asc-santo** [comment]
If this can help, you can see that there is a problem with the width of the pane, when you are in the search (Ctrl+F) mode, you can see that the part more to the right is partially hidden (the "X" is not fully visible)
(EDIT: i changed some colors don't worry about it)
![image](https://user-images.githubusercontent.com/82507937/151186648-49d65ae7-f9ca-4467-bcce-5d907c6b5368.png)

**Comment by ceciliamay** [comment]
Hello there! LYT Mode developer 🔦 here - I found a fix for this! Should come fixed in the next update 😄 Thank you so much for reporting this issue!! (It also helped me fix the bug on my own theme, Primary_

**Comment by asc-santo** [comment]
Great!

**Comment by ceciliamay** [comment]
This has been fixed in [Release v.1.1](https://github.com/nickmilo/LYT-Mode/releases/tag/v.1.1.0)! 🎉
Thank you so much for submitting this issue! Please update your themes :D
