### ISSUE TITLE
Problem with creating and editing text in Excalidraw notes

### ISSUE THREAD

**Issue by asc-santo** [nickmilo/LYT-Mode#13]
When putting text inside of an Excalidraw block, the text is initially shown somewhere more on the right then its real location, which is kinda annoying especially if the block has centered text inside (instead of alligned on the left side) because, when editing it, the text is shown way more further on the left. I don't know where can this bug come from, but previoulsy i was using the Cybertron theme and it wasn't like this.

**Comment by ceciliamay** [comment]
This has been fixed in [Release v.1.1](https://github.com/nickmilo/LYT-Mode/releases/tag/v.1.1.0)! 🎉
Thank you so much for all the issues you've submitted! Please update your theme :D

**Comment by asc-santo** [comment]
I'm just trying to use my system with the least friction possible ahahaha thank you for solving them :DD
