### ISSUE TITLE
highlighted Inline code obscures text in a dark square 

### ISSUE THREAD

**Issue by jyrodgers** [nickmilo/LYT-Mode#15]
When I highlight text ( surround it with equal signs) and some of that text is inline code ( surround it with backticks) then in preview mode the inline code is obscured by a dark rectangle.

**Comment by ceciliamay** [comment]
Hello! LYT Mode developer here~ Do you have a screenshot of how this looks like?

**Comment by jyrodgers** [comment]
The text:

```
==Additional key-value pairs can be added by using the `--from-literal` option multiple times.==
```

Renders like this

![CleanShot 2022-01-27 at 14 29 32](https://user-images.githubusercontent.com/4572538/151454279-a0474cb8-c5b8-40e8-af96-9039b926dc68.png)

How it looks selected

![CleanShot 2022-01-27 at 14 32 55](https://user-images.githubusercontent.com/4572538/151454594-9d53cdb5-e158-474e-82cd-a96228d9a0ac.png)

**Comment by ceciliamay** [comment]
This has been fixed in [Release v.1.1](https://github.com/nickmilo/LYT-Mode/releases/tag/v.1.1.0)! 🎉
Thank you so much for submitting this issue! Please update your themes :D
