### ISSUE TITLE
Embedded audio files take up too much space in preview mode

### ISSUE THREAD

**Issue by asc-santo** [nickmilo/LYT-Mode#16]
As title says, this is the editor mode (live preview)
![image](https://user-images.githubusercontent.com/82507937/151389815-a2adc8af-5fc8-4227-a266-e9927fdfa310.png)

And this is the preview mode, the block is bigger and there is a lot of useless margin in between
![image](https://user-images.githubusercontent.com/82507937/151389913-bf8fcadb-0c83-4e58-a94e-cb0775271c30.png)

**Comment by ceciliamay** [comment]
Thank for reporting this @asc-santo !! Unfortunately, I can't seem to replicate that on my end. Do you have a sample/demo file you could share?

**Comment by asc-santo** [comment]
Sure, here it is an audio file, that's the extention used by xiaomi audio notes, you can just embed it in a .md note ![[AUDIO.aac]]
[AUDIO.zip](https://github.com/nickmilo/LYT-Mode/files/7963994/AUDIO.zip)

**Comment by ceciliamay** [comment]
okay so i just checked this out. it seems to be a problem with how obsidian renders the embeded files that are placed next to each other. i checked it on the default obsidian theme just to be sure.

if you add an extra empty line between the 2 files, it removes the weird spacing in preview mode! refer to the gif below:
![weird-spacing-on-embeded](https://user-images.githubusercontent.com/90643719/151667215-48d7d11e-28df-4784-bc3b-ec7bcbd0f36a.gif)

let me know if this works!!

**Comment by ceciliamay** [comment]
Hey there @asc-santo , hope you've seen my reply to you above! I will be closing this now 😄 Let me know if there are any other issues!
