### ISSUE TITLE
Inputs in extesions are too long

### ISSUE THREAD

**Issue by curtismchale** [nickmilo/LYT-Mode#18]
The screenshot below is the Vantage plugin. The input for the word I'm trying to add to the search is far too long and pushes the buttons off the page.

<img width="1031" alt="CleanShot 2022-01-31 at 10 36 27@2x" src="https://user-images.githubusercontent.com/74561/151852582-6eb18315-190b-4a5c-85d5-fc755e2748e5.png">

For context, same screen with the default theme.

<img width="1356" alt="CleanShot 2022-01-31 at 10 37 44@2x" src="https://user-images.githubusercontent.com/74561/151852739-00830ccb-8253-4170-a5de-38bbe27965b7.png">

Similar idea for the Kanban plugin and it's search field.

LYT theme:
<img width="1625" alt="CleanShot 2022-01-31 at 10 38 48@2x" src="https://user-images.githubusercontent.com/74561/151852878-7e1f891d-5c4d-4934-87e9-84b759240e92.png">

Default theme: 
<img width="456" alt="CleanShot 2022-01-31 at 10 38 07@2x" src="https://user-images.githubusercontent.com/74561/151852800-da613ebe-fc96-4f3f-a453-94f1dddeb1c8.png">

**Comment by ceciliamay** [comment]
This has been fixed in [Release v.1.1](https://github.com/nickmilo/LYT-Mode/releases/tag/v.1.1.0)! 🎉
Thank you so much for submitting this issue!
