### ISSUE TITLE
Title & some headers difficult to see in PDF exports

### ISSUE THREAD

**Issue by thatdwayne** [nickmilo/LYT-Mode#2]
I love how the theme looks in dark mode, but when I export to PDF, headers 1, 2, and 3 are difficult to see in the exported pdf.

It looks like a shadow is being applied, which helps a bit, but not enough (IMO). I know Cecilia modifies the exported text in Primary to make it black on pdf exports - maybe something similar here?

I've attached an example of an exported PDF.

[Test Title (which is really an H1).pdf](https://github.com/nickmilo/LYT-Mode/files/7841010/Test.Title.which.is.really.an.H1.pdf)

**Comment by nickmilo** [comment]
Yep, that's the nature of dark mode themes. I would suggest switching themes to the Default theme's Light Mode whenever you want to export a PDF. 

If anyone out there knows of alternative solutions, feel free to share!

**Comment by thatdwayne** [comment]
I'm not sure of the mechanics of it, but I've noticed that the "Gitsidian" theme does this automatically - you edit in dark mode, but Previews show up as if you'd switched to light mode. Then when you export to PDF, it shows up "normal" there, as well.

**Comment by br4in** [comment]
> Yep, that's the nature of dark mode themes. I would suggest switching themes to the Default theme's Light Mode whenever you want to export a PDF.
> 
> If anyone out there knows of alternative solutions, feel free to share!

@nickmilo - @Basquiiiat - You can add a print media query in the CSS file to choose how a note will appear in PDF.

The code below removes the text shadow and changes the color of body and headers to `var(--color-slate-900)`.

`@media print {
	/* Remove drop-shadow */
	:root {
		--header-shadow-size: 0;
	}
	
	/* Change body text color */
	.theme-dark .markdown-source-view,
	.theme-dark .markdown-preview-view {
		color: var(--color-slate-900);
	}

	/* Change headers text color */
	body.theme-dark {
		--h1-color: var(--color-slate-900);
		--h2-color: var(--color-slate-900);
		--h3-color: var(--color-slate-900);
		--h4-color: var(--color-slate-900);
		--h5-color: var(--color-slate-900);
		--h6-color: var(--color-slate-900);
		color: var(--color-slate-900);
	}
}`
