### ISSUE TITLE
Indicate by color that a heading is in a comment block

### ISSUE THREAD

**Issue by jyrodgers** [nickmilo/LYT-Mode#20]
My request is to indicate by color that a heading is in a comment block in a similar way as is done with regular test. This would be a useful visual reminder for the user that the content is hidden from view in preview mode.

Here is a screen shot that shows the difference ( in Live Preview Mode ) between regular text and commented text as well as the similarity between regular headings and commented headings.

![CleanShot 2022-02-10 at 12 04 20](https://user-images.githubusercontent.com/4572538/153487683-4f3098da-bfd7-420b-97e1-4b87e984b6ce.png)

**Comment by ceciliamay** [comment]
Thank you for the suggestion!! @jyrodgers - a change has been added in v.1.1.1 and they look like this:
![image](https://user-images.githubusercontent.com/90643719/161407572-bdd936b1-57f0-4c98-9af2-3dfda4063322.png)
