### ISSUE TITLE
Wikilinks color bleeding over to adjacent letter

### ISSUE THREAD

**Issue by everruler12** [nickmilo/LYT-Mode#23]
As shown in the screenshot, in `[[future-proof]]ing` where there is no space after the closing brackets, and the next letter gets the same color as the link.

Happens in both Live Preview and Reading Mode.
![image](https://user-images.githubusercontent.com/64292121/153515286-20acc881-c96b-4ad4-8e32-2a1821e6c798.png)

**Comment by everruler12** [comment]
After further testing, I discovered this only happens with `i` and `l` which are the thinnest letters. The links are also clickable on that last letter, so this may not be an issue with the theme at all, and is instead aan Obsidian parsing issue.

**Comment by ceciliamay** [comment]
Interesting bug! I'm glad you found out that it was a parsing issue. This would be a good bug to report on the forums!! Again, thanks for reporting 😄

**Comment by everruler12** [comment]
So, this isn't a problem in the default theme. I narrowed it further to the font: DM Sans.
Removing 'DM Sans' from `--font-sans-2` makes the issue go away.
I think it has to do with the glyphs. Notice how the `i` gets a little extra horizontal line added to connect it with the `f` when right next to it.
![image](https://user-images.githubusercontent.com/64292121/153790940-dc7af39b-5727-4b97-9081-2216c268e6c9.png)

So ultimately, I don't think it's an Obsidian problem or an issue with this CSS theme, but a bug in the underlying browser renderer.
