### ISSUE TITLE
Indent files in the directory tree

### ISSUE THREAD

**Issue by Quantentunnel** [nickmilo/LYT-Mode#24]
It would be nice if the files in the directory tree are indented as well. It is sometimes difficult to distinguish them from the folders.

Here how it looks like on cybertron:
![cybertron](https://user-images.githubusercontent.com/2110463/154037026-808d36a4-8cb7-426b-b4ef-fdb679889b2c.png)

and here on LYT:
![lyt](https://user-images.githubusercontent.com/2110463/154037054-dc3bc72f-c14b-4d83-80e9-4552c7b13a4f.png)

**Comment by ceciliamay** [comment]
hello there @Quantentunnel ! I talked to Nick with this but he prefers that the indent paddings stay the same, sorry. If you'd like them to be padded a little bit more, you can create a snippet for it instead! 😊
