### ISSUE TITLE
No Margin Padding

### ISSUE THREAD

**Issue by SamuelYancy** [nickmilo/LYT-Mode#25]
I am not sure if margin padding is the correct term, but below is a screen shot of the issue. This occurs when I am in the reading view with 4 notes open in a 2x2 grid.

## LYT Reading View - Text Starts at the very left of the window
<img width="457" alt="Screen Shot 2022-02-16 at 16 14 55" src="https://user-images.githubusercontent.com/62109721/154366794-09dc84d4-4d12-47e5-bb07-8b178c1ccf3d.png">

## LYT Edit View - Text has a bit more space but is still close the the left edge
<img width="457" alt="Screen Shot 2022-02-16 at 16 15 00" src="https://user-images.githubusercontent.com/62109721/154366926-69a23fb0-0d99-4352-91d1-1fe9be2357d1.png">

For Comparison here are the same screen shots but with the Things Theme.

## Things Theme Reading View Screenshot - Notice the spacing of the left.
<img width="457" alt="Screen Shot 2022-02-16 at 16 15 40" src="https://user-images.githubusercontent.com/62109721/154366671-d0a1c3a8-d294-4d1d-bac3-10506bfde167.png">

## Things Theme Edit View Screenshot - this spacing is reflected in the edit view as well
<img width="457" alt="Screen Shot 2022-02-16 at 16 15 46" src="https://user-images.githubusercontent.com/62109721/154367085-7492ed29-0279-4f9e-b8e5-7dc6e3e46862.png">

**Comment by beglitched** [comment]
I had the same problem. I had Readable Line Length turned OFF in Editor settings. Turn it back on and you should see margins.

**Comment by SamuelYancy** [comment]
This did not fix it for me.

**Comment by ceciliamay** [comment]
this will be fixed in the coming update! hold on just a little bit more guys :)

**Comment by ceciliamay** [comment]
@SamuelYancy , and others - this has been fixed in [v.1.1.1](https://github.com/nickmilo/LYT-Mode/releases/tag/v.1.1.1)! Thank you so much for reporting! 🎉
