### ISSUE TITLE
Excalidraw Tools Panel Mouse Dragging: floats to right bottom screen

### ISSUE THREAD

**Issue by zsviczian** [nickmilo/LYT-Mode#26]
seems to be theme related: [#493](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/493)

**Comment by ceciliamay** [comment]
This has been fixed in [v.1.1.1](https://github.com/nickmilo/LYT-Mode/releases/tag/v.1.1.1)! Thank you so much for reporting! 🎉
