### ISSUE TITLE
LYT Mode not compatible with Hover-Editor

### ISSUE THREAD

**Issue by LordMartron94** [nickmilo/LYT-Mode#28]
I discovered the LYT Mode theme is not compatible with the plugin Hover-Editor yet, since the minimize button of Hover-Editor isn't working when having LYT Mode on. With the default theme, for example, it does work.

Aside from that, it would be nice to have the custom emotes used by Eleanor Konik in the theme :)

Source:
https://www.youtube.com/watch?v=8IL0wFUT6XQ

**Comment by nickmilo** [comment]
Haha, you read my mind. Both are being discussed to be added to LYT Mode.
