### ISSUE TITLE
Long headings are partially hidden on iPad

### ISSUE THREAD

**Issue by albfaggion** [nickmilo/LYT-Mode#3]
![IMG_1058](https://user-images.githubusercontent.com/87950446/149670658-d6deb241-7fe5-4969-9453-96a91f6623a5.png)

As you cannot see, when I have a long heading, LYT-mode shows only the first words. It occurs especially on edit mode. I believe this issue is related to another one: highlighted words also get invisible on iPad.

**Comment by nickmilo** [comment]
This happens to me too. Apparently, it isn't happening for everyone. We are troubleshooting this.

**Comment by albfaggion** [comment]
Thank you for your reply. I hope you can fix especially the highlight issue on mobile because I've been following Thiago Forte’s advice to always highlight the main idea in a long note to save time when searching for specific ideas in the future.

**Comment by nickmilo** [comment]
Hey @albfaggion , can you show the example of highlighting words not showing on the iPad? I can't replicate that on my iPhone.

**Comment by albfaggion** [comment]
![346D1FD6-6DA5-445B-91C1-70957B760C83](https://user-images.githubusercontent.com/87950446/149920717-39aed6f5-16c8-47db-9b38-16aac32014a9.png)

Hello @nickmilo! This is an example from my iPhone. But the same happens on my iPad. It happens to every single highlight. By the way, I used to have basically the same issue with Cybertron. But it never happens with other themes. Thank you for your attention as always.

**Comment by jetfighter82** [comment]
This is also happening for me on my iPhone. When the heading goes over two lines, the text becomes invisible, but it's still there.

**Comment by ceciliamay** [comment]
This issue does not occur on Android, so I currently am clueless on how to go about this issue. With that being said, we are offering an alternative styling option you can choose for both Headers and Highlights through the Style Settings Plugin (available on the Community Plugins store) that can fix these issues! Simply download the Style Settings Plugin, and with LYT Mode installed, choose "Safe Style" on the drop down, for both Headers and Highlights.

![image](https://user-images.githubusercontent.com/90643719/152686709-cb4bfbc0-f804-45a9-980c-d62cf18237f2.png)

We are still hoping that you'll be able to use the Preferred Style in the future, so we will continue to identify the cause and look for a more elegant solution.

This, along with other updates, can be read in the [Changelog for LYT Mode v.1.1 here](https://github.com/nickmilo/LYT-Mode/releases/tag/v.1.1.0)! Please update your themes :D

**Comment by albfaggion** [comment]
Thank you so much! Safe style is good enough for me. So now I can use my favorite theme again :D



---

andreafaggion.com

**Comment by jetfighter82** [comment]
Fabulous, thank you. Safe style is working fine for me too!
