### ISSUE TITLE
Issue: Side bars overlapping the notch in iPhone 13 Pro

### ISSUE THREAD

**Issue by paolo-santucci** [nickmilo/LYT-Mode#30]
As you can see in the pictures below, the top margin of the side bars isn't enough to avoid the phone's notch overlapping Obsidian. 

![image](https://user-images.githubusercontent.com/17023798/160556359-b6c746cf-9132-4aa0-b1f6-2ce25f038143.png)

![image](https://user-images.githubusercontent.com/17023798/160556405-9156acd4-f2df-493e-b3c9-dbae33d2a373.png)

**Comment by nickmilo** [comment]
Just reviewed on a smaller iPhone with notch and couldn't replicate. Will try to test an iPhone 13 pro later

**Comment by paolo-santucci** [comment]
Thanks, let me know if I can help you in the debugging process.

**Comment by paolo-santucci** [comment]
I just tried disabling all the community plugins and it's showing correctly. 

I'll do some further investigation to pinpoint what's causing the issue.

**Comment by paolo-santucci** [comment]
OK, it was my fault! 🫣

I had **Hider** enabled with _Hide Title Bar_ on. 

I'm sorry for the false alarm.

**Comment by ceciliamay** [comment]
Woops! Haha! Good to know you've solved it @perfidopelato ! Great job. I'll close this now. Thanks for reporting!! ❤️🙌
