### ISSUE TITLE
Checkbox line spacing is big for some people, anyone else?

### ISSUE THREAD

**Issue by nickmilo** [nickmilo/LYT-Mode#9]
(From bonnie gray on Youtube)
LOVE this theme, Nick. It's great. I've applied it and am using it happily. I didn't know that you could create checkboxes to check to-dos off, though! Weirdly, with the LYT theme my spacing between checkbox lines is not tight like yours is here. It's quite spaced apart, which is putting me off using it. Any ideas? Everything else has fantastic tight spacing.

**Comment by digislexia** [comment]
Also the text is not aligned well with the checkbox in "Reading" mode
![image](https://user-images.githubusercontent.com/31546752/150415357-4dcf5f11-c7ee-4e5a-9cb7-9b3963e46e6d.png)

**Comment by thatdwayne** [comment]
It looks fine for me - do you have any css snippets that might be interacting oddly?
![image](https://user-images.githubusercontent.com/50638113/150421402-13ab1d94-6526-47b2-98ff-ad507914c75e.png)

FWIW, I'm on a Mac. Obsidian v0.13.21 and LYT Mode version from the community themes.

**Comment by jetfighter82** [comment]
![2022-01-20_21-49-45](https://user-images.githubusercontent.com/1951708/150427898-2bfebc30-172c-4502-8cb6-48a4a80192be.jpg)

Hi Nick, it was me who posted on YouTube. Thanks for pointing me in the direction of this thread! Here's a screenshot of how it appears for me. I'm using the Windows 10 version.

**Comment by ceciliamay** [comment]
This has been fixed in [Release v.1.1](https://github.com/nickmilo/LYT-Mode/releases/tag/v.1.1.0)! 🎉
Thank you all so so much for submitting this issue! Please update your themes and let me know how it goes! :D
